# Generated by Django 4.1.5 on 2023-02-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=122)),
                ('EMAIL', models.CharField(max_length=122)),
                ('CONTACTNO', models.CharField(max_length=122)),
                ('MESSAGE', models.CharField(max_length=200)),
                ('date', models.TimeField()),
            ],
        ),
    ]
