# Generated by Django 4.1.5 on 2023-02-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='CONTACTNO',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='EMAIL',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='MESSAGE',
            new_name='massage',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='NAME',
            new_name='name',
        ),
    ]
