# Generated by Django 4.1.5 on 2023-02-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contactno_contact_contact_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_no',
            new_name='Phone',
        ),
    ]
